### ISSUE TITLE
Farmer does not start - 'SpendBundle' is not defined

### ISSUE THREAD

**Issue by rocketeeer** [Olive-blockchain/Olive-blockchain#69]
Running on Ubuntu 20.04.  I followed the 'Linux install instructions' in the wiki section and ran `olive keys generate`.  But I get the following error when I run `olive farm summary`:

```
Traceback (most recent call last):
  File "/home/myhome/git/Olive-blockchain/venv/bin/olive", line 33, in <module>
    sys.exit(load_entry_point('olive-blockchain', 'console_scripts', 'olive')())
  File "/home/myhome/git/Olive-blockchain/olive/cmds/olive.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/myhome/git/Olive-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/myhome/git/Olive-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/myhome/git/Olive-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/myhome/git/Olive-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/myhome/git/Olive-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/myhome/git/Olive-blockchain/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/myhome/git/Olive-blockchain/olive/cmds/farm.py", line 58, in summary_cmd
    from .farm_funcs import summary
  File "/home/myhome/git/Olive-blockchain/olive/cmds/farm_funcs.py", line 9, in <module>
    from olive.rpc.wallet_rpc_client import WalletRpcClient
  File "/home/myhome/git/Olive-blockchain/olive/rpc/wallet_rpc_client.py", line 13, in <module>
    class WalletRpcClient(RpcClient):
  File "/home/myhome/git/Olive-blockchain/olive/rpc/wallet_rpc_client.py", line 236, in WalletRpcClient
    async def recover_pool_nft(self, launcher_hash: str, contract_hash: str, coins: List[Coin]) -> SpendBundle:
NameError: name 'SpendBundle' is not defined
```

Output of `olive version`:
```
1.0.1
```

But the latest release is `v1.0.20`

**Comment by rocketeeer** [comment]
This seems related to: https://github.com/Olive-blockchain/Olive-blockchain/issues/68

**Comment by rocketeeer** [comment]
I implemented the change from https://github.com/Olive-blockchain/Olive-blockchain/pull/70 locally and then ran `olive stop -d all` and `olive start all`.

My farmer is now syncing with no errors.  Olive version is still `1.0.1`
