### ISSUE TITLE
[BUG] Command 'olive farm summary' doesn't work.

### ISSUE THREAD

**Issue by GregoryGum** [Olive-blockchain/Olive-blockchain#71]
Debian 10.
Installation through command line without UI.

Traceback (most recent call last):
  File "/home/chia/ChiaForks/Olive-blockchain/venv/bin/olive", line 33, in <module>
    sys.exit(load_entry_point('olive-blockchain', 'console_scripts', 'olive')())
  File "/home/chia/ChiaForks/Olive-blockchain/olive/cmds/olive.py", line 77, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/chia/ChiaForks/Olive-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/chia/ChiaForks/Olive-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/chia/ChiaForks/Olive-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chia/ChiaForks/Olive-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chia/ChiaForks/Olive-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chia/ChiaForks/Olive-blockchain/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/chia/ChiaForks/Olive-blockchain/olive/cmds/farm.py", line 58, in summary_cmd
    from .farm_funcs import summary
  File "/home/chia/ChiaForks/Olive-blockchain/olive/cmds/farm_funcs.py", line 9, in <module>
    from olive.rpc.wallet_rpc_client import WalletRpcClient
  File "/home/chia/ChiaForks/Olive-blockchain/olive/rpc/wallet_rpc_client.py", line 13, in <module>
    class WalletRpcClient(RpcClient):
  File "/home/chia/ChiaForks/Olive-blockchain/olive/rpc/wallet_rpc_client.py", line 236, in WalletRpcClient
    async def recover_pool_nft(self, launcher_hash: str, contract_hash: str, coins: List[Coin]) -> SpendBundle:
NameError: name 'SpendBundle' is not defined

**Comment by GregoryGum** [comment]
I see the solution.
https://github.com/Jsewill/Olive-blockchain/commit/f7251cf70625845d44fcc9a61c2c183b8d3809f8
